### ISSUE TITLE
When n_classes>1, how 'self.label_encoder‘ do for label(float)?

### ISSUE THREAD

**Issue by luozhengdong** [yandex-research/tabular-dl-tabr#10]
‘context_y_emb = self.label_encoder(candidate_y[context_idx][..., None])’  is W(yi) of Step-1. Adding context labels. Here candidate_y[context_idx] are the labels of retrieval samples,
When classification task, n_classes>1,  candidate_y[context_idx] value are integers., 
so self.label_encoder do:
```
           else nn.Sequential(
                nn.Embedding(n_classes, d_main), delu.nn.Lambda(lambda x: x.squeeze(-2)) 
            )
```
I would like to know how to make this nn.Sequential operate on non-integer numbers? 
For example, label goes from {Tensor:(512,96,)}=tensor([[7, 7, 7,  ..., 8, 0, 7],
        [8, 8, 8,  ..., 8, 8, 8],
        [2, 2, 2,  ..., 6, 2, 1],
        ...,
        [5, 5, 5,  ..., 5, 5, 5],
        [5, 5, 5,  ..., 5, 5, 5],
        [5, 5, 5,  ..., 5, 5, 5]], device='cuda:0') to 
        {Tensor:(512,96,)}=tensor([[7.2188, 7.2188, 7.2188,  ..., 7.7451, 0.0000, 7.2188],
        [7.7451, 7.7451, 7.7451,  ..., 7.7451, 7.7451, 7.7451],
        [1.9530, 1.9530, 1.9530,  ..., 6.3834, 1.9530, 0.9778],
        ...,
        [5.5154, 5.5154, 5.5154,  ..., 5.5154, 5.5154, 5.5154],
        [5.5154, 5.5154, 5.5154,  ..., 5.5154, 5.5154, 5.5154],
        [5.5154, 5.5154, 5.5154,  ..., 5.5154, 5.5154, 5.5154]],
       device='cuda:0').

err: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)

Thanks~

**Comment by luozhengdong** [comment]
```
#my code:
context_y=[[class_rank[key.item()] for key in row] for row in candidate_y[context_idx]]
context_y=torch.tensor(context_y)[..., None].to(device) #tensor value float
context_y_emb = self.label_encoder(context_y)
values = context_y_emb + self.T(k[:, None] - context_k)
```
'''
#bug as:
Traceback (most recent call last):
File "/anaconda3/envs/torch/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
value_or_values = func(trial)
File "/bin/tune.py", line 160, in objective
report = function(raw_config, Path(tmp) / 'output') #the objective function, in turn, calls the function = "bin.tabr.main"
File "/bin/tabr.py", line 593, in main
loss, new_chunk_size = lib.train_step(
File "/lib/deep.py", line 467, in train_step
raise RuntimeError('Not enough memory even for batch_size=1')
RuntimeError: Not enough memory even for batch_size=1
[W 2023-11-01 21:03:39,257] Trial 0 failed with value None.
Thanks~
'''
 The dataset is still otto in tabr, I just did some processing of the label to float for my personal needs.

**Comment by Yura52** [comment]
This customization seems to go significantly beyond our paper, so I am unlikely to help here, sorry for that! I can say though that error messages are usually very helpful, for example, the error above says that there is not enough CUDA memory:

```
RuntimeError: Not enough memory even for batch_size=1
```

**Comment by Yura52** [comment]
If you provide more details on what you are trying to do, perhaps, I can give a more detailed answer.
