### ISSUE TITLE
How to calculate the final result in the results of 100trails

### ISSUE THREAD

**Issue by luozhengdong** [yandex-research/tabular-dl-tabr#15]
Hello,
From your code, it is clear that n_trails=100, but I find that the last trail result is not optimal, and the paper doesn't seem to go into detail about this, so may I ask what the results reported in the paper do with these 100 trail results? Optimal or average?

And what are the 15 random seeds used in the test, and are they not used in the train?

Thanks~

**Comment by Yura52** [comment]
Hello,

After each of 100 trials, [this function](https://github.com/yandex-research/tabular-dl-tabr/blob/6edd5068b5b267ef45cb501b30cd64cbb981cf44/bin/tune.py#L161) is called, which saves only _the best_ out of 100 trials. The scores of trials is not monotonically increasing, so it is _not_ a bug when the last trial is not the best one.

Then, [the best configuration](https://github.com/yandex-research/tabular-dl-tabr/blob/6edd5068b5b267ef45cb501b30cd64cbb981cf44/bin/evaluate.py#L35) (corresponding to the best trial) is evaluated under 15 random seeds here.

**Comment by luozhengdong** [comment]
![image](https://github.com/yandex-research/tabular-dl-tabr/assets/44635958/22a3071f-4e60-47c6-aafc-67b30630932a)

In this code, function has been identified as 'bin.tabr_oroc.main' by " python bin/evaluate.py exp/tabr_oroc/regression-num-medium-2-wine_quality/4-tuning --function bin.tabr_oroc.main
". Is it wrong to identify function as None? I'm getting a bug when I run it.
![image](https://github.com/yandex-research/tabular-dl-tabr/assets/44635958/1b7e1887-b272-44bd-bf2c-34c14f7cee06)

**Comment by Yura52** [comment]
When you pass the tuning output directory to `bin/evaluate.py`, the function name will be [automatically extracted](https://github.com/yandex-research/tabular-dl-tabr/blob/6edd5068b5b267ef45cb501b30cd64cbb981cf44/bin/evaluate.py#L34) from `report.json` in that directory, so you don't have to provide it explicitly.

**Comment by luozhengdong** [comment]
```
assert function is None
```
is before
```
tuning_report = lib.load_report(path)
```
![image](https://github.com/yandex-research/tabular-dl-tabr/assets/44635958/e603116c-3f85-4fb8-9e71-214cc314bb53)
The bug is at assert function is None
![image](https://github.com/yandex-research/tabular-dl-tabr/assets/44635958/717f3785-b042-40f7-9fd9-28d83bdad962)

**Comment by Yura52** [comment]
Yes, the error traceback indicates that you should remove `--function bin.tarb_oroc.main` from your command

**Comment by luozhengdong** [comment]
This is ok.
And then you need to change the github here:
![image](https://github.com/yandex-research/tabular-dl-tabr/assets/44635958/ad34f22e-d9b0-420d-8162-a81ddaf410a2)

**Comment by Yura52** [comment]
Thank you for reporting the issue!
