### ISSUE TITLE
OneHotEncoder of Cat features

### ISSUE THREAD

**Issue by Reederey87** [yandex-research/tabular-dl-tabr#2]
Hi. Is OneHotEncoder betters working with suggested architecture? Did you test others (OrdinalEncoder, etc)?

**Comment by Yura52** [comment]
Hi! In this project, we did not explore alternatives to one-hot encoding. In that regard, TabR is no different from MLP, ResNet, and many other DL models, for which encoding of categorical features is an orthogonal design aspect. So one is free to try other encoding schemes, and the one-hot encoding was used just as a simple "default" strategy.

**Comment by Yura52** [comment]
Feel free to reopen the issue if needed!
