### ISSUE TITLE
How do I get the ± values in my experimental results?

### ISSUE THREAD

**Issue by luozhengdong** [yandex-research/tabular-dl-tabr#20]
Hi, bothering you again~
    For example, in the wine quality dataset, the ensemble performance is 0.620±0.007, and it is known that `go.py` will get three sets of scores, so how to get this ±0.007?

**Comment by Yura52** [comment]
Hi, you will have to compute it manually. For example, this is how you can compute the mean and the standard deviation of the score of MLP on california (the same applies to ensembles and all other algorithms):

```python
import json
import statistics
from pathlib import Path

scores = [
    json.loads(x.joinpath('report.json').read_text())['metrics']['test']['score']
    for x in Path('exp/mlp/california/0-evaluation').iterdir()
    if x.is_dir()
]
print(f'{statistics.mean(scores)} +- {statistics.stdev(scores)}')
```

**Comment by luozhengdong** [comment]
OK! Thanks
