### ISSUE TITLE
Can I use this code model as a backbone network for academic paper publishing？

### ISSUE THREAD

**Issue by luozhengdong** [yandex-research/tabular-dl-tabr#22]
If I use this work as a backbone network, and add my own modules, then publish an academic paper, does that constitute copyright infringement? Of course， I would state that I am citing your work.

**Comment by Yura52** [comment]
Hi! It is totally fine to use this repository in your work, given that this repository and the corresponding paper are properly cited and described.

In practice, I recommend the following:
- Cite the paper.
- In the paper, when describing your setup, explain that you run experiments based on the official implementation of our paper.
- In your copy of this repository, in `README.md`, add a note clarifying that your repository was started as a copy of this repository. Example:

"""
This repository was started as a copy of the following repository: https://github.com/yandex-research/tabular-dl-tabr (commit: `<commit id>`)
"""

Where `commit id` is a commit in the [history](https://github.com/yandex-research/tabular-dl-tabr/commits/main/) that you used as a starting point.

If you are interested in more formal details, see the `LICENSE` file at the root of this repositor (btw, it should be Apache 2.0, not MIT, I will fix that soon).

**Comment by luozhengdong** [comment]
OK, Thanks!

**Comment by Yura52** [comment]
In future, if an issue that you created is resolved, feel free to close it :)
