### ISSUE TITLE
Datasets origin

### ISSUE THREAD

**Issue by caiocrm** [yandex-research/tabular-dl-tabr#25]
Hi, congratulations for the great work!

Just a few questions about the "why" datasets from https://github.com/LeoGrin/tabular-benchmark (https://huggingface.co/datasets/inria-soda/tabular-benchmark). I noticed that the dataset online news is not on the benchmark original benchmark. 

Also the classif-cat-medium-0-compass which i imagine is the compas-two-years is very different. 

The one you provided in https://huggingface.co/datasets/puhsu/tabular-benchmarks/resolve/main/data.tar have this characteristics:
{
    "name": "classif-cat-medium-1-compass",
    "id": "classif-cat-medium-1-compass",
    "train_size": 10000,
    "val_size": 1993,
    "test_size": 4651,
    "n_num_features": 8,
    "n_cat_features": 7,
    "n_bin_features": 2
}

while the original (https://www.openml.org/search?type=data&sort=runs&id=45039&status=active) have 11 features and 4966 lines in total.

I'm comparing with my own algorithm, i'm using your results on the "why" benchmark as reference. Thanks in advance!

**Comment by Yura52** [comment]
Hi! The "OnlineNewsPopularity" dataset is mentioned in Section A.1.4 of [the paper](https://arxiv.org/pdf/2207.08815v1), and the "compass" dataset is mentioned in Section A.1.3. Also, there are [tables](https://github.com/LeoGrin/tabular-benchmark/blob/9d54cf53d9fd3159e367e70a00005f4fcbf2c79d/analyses/datasets) with dataset properties, and OnlineNewsPopularity is presented [here](https://github.com/LeoGrin/tabular-benchmark/blob/9d54cf53d9fd3159e367e70a00005f4fcbf2c79d/analyses/datasets/numerical_regression.csv#L103), and compass is presented [here](https://github.com/LeoGrin/tabular-benchmark/blob/9d54cf53d9fd3159e367e70a00005f4fcbf2c79d/analyses/datasets/categorical_classif.csv#L569).

**Comment by Yura52** [comment]
Feel free to reopen the issue if needed!

**Comment by caiocrm** [comment]
I apologize, I was very sloppy and shouldn't have taken up your time. Even so, you responded kindly, thank you very much!
