### ISSUE TITLE
? bug: delu.nn.Lambda(lambda x: x.squeeze(-2))  

### ISSUE THREAD

**Issue by luozhengdong** [yandex-research/tabular-dl-tabr#7]
When the classification task is performed, n_classes>1,call self.label_encoder of tabr.py, and there is a bug:
ValueError: fn must be a function from `torch` or a method of `torch.Tensor`, but ...
How do I fix this?

**Comment by Yura52** [comment]
Try this: `pip install delu==0.0.15`

Overall, to run the code in this repository and avoid issues related to library versions, it is recommended to set up the environment as described [in this section](https://github.com/yandex-research/tabular-dl-tabr?tab=readme-ov-file#set-up-the-environment).
