### ISSUE TITLE
bug:when eval, AttributeError: module 'torch.cuda' has no attribute 'OutOfMemoryError'

### ISSUE THREAD

**Issue by luozhengdong** [yandex-research/tabular-dl-tabr#8]
After the training of an epoch, when evaluating, eval_batch_size=32768, meaning that all the validation sets are treated as a batch, when evaluating the otto dataset, there is insufficient GPU memory, how to improve this? When evaluating the otto dataset, the GPU is running out of memory? bug as:
RuntimeError: CUDA out of memory. Tried to allocate 2.25 GiB (GPU 0; 11.17 GiB total capacity; 5.74 GiB already allocated; 2.04 GiB free; 7.13 GiB reserved in total by PyTorch)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/anaconda3/envs/torch/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "~/bin/tune.py", line 160, in objective
    report = function(raw_config, Path(tmp) / 'output')  #the objective function, in turn, calls the function = "bin.tabr.main"
  File "~/bin/tabr.py", line 592, in main
    metrics, predictions, eval_batch_size = evaluate(
  File "~/anaconda3/envs/torch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File ~/bin/tabr.py", line 537, in evaluate
    if not lib.is_oom_exception(err):
  File "~/lib/util.py", line 493, in is_oom_exception
    return isinstance(err, torch.cuda.OutOfMemoryError) or any(
AttributeError: module 'torch.cuda' has no attribute 'OutOfMemoryError'
[W 2023-10-31 20:35:10,691] Trial 0 failed with value None.
thanks~

**Comment by Yura52** [comment]
What is the output of the following command?

`python -c "import torch; print(torch.__version__)"`

**Comment by Yura52** [comment]
Thanks. According to the error message, `torch.cuda.OutOfMemoryError` is not available in your version of `torch`, and CUDA-out-of-memory errors are raised as `RuntimeError`. So, in the function `is_oom_exception`, I recommend replacing
```
return isinstance(err, torch.cuda.OutOfMemoryError) or any(...)
```
with
```
return isinstance(err, RuntimeError) or any(...)
```

Does this help?

**Comment by luozhengdong** [comment]
yeah, the code is running and it looks like this debug is working.
Thanks~

**Comment by Yura52** [comment]
Great! In future, feel free to close issues if they are resolved :)

**Comment by luozhengdong** [comment]
![image](https://github.com/yandex-research/tabular-dl-tabr/assets/44635958/17cb8bdc-dee2-4257-b1c9-8e3461e17b2b)
How did eval_batch_size = 8192 come about, and what part of the code is it
